### PR TITLE
Fix create index show result before showing creating progress

### LINKED ISSUE #201: GUI: create index show result before  creating.
https://user-images.githubusercontent.com/185051/127980007-4e5ccb2c-fffb-4392-b91e-770f7eb947cd.mov

### PR DESCRIPTION
**Pull request by Tumao727**
fix #201 

fix

change default status from `InProgress` to empty string and add loading until fetching finished

### CODE REVIEW

File: client/src/pages/schema/IndexTypeElement.tsx [hunk 1]
```diff
@@ -86,18 +92,15 @@ const IndexTypeElement: FC<{
   const DeleteIcon = icons.delete;
 
   const fetchStatus = useCallback(async () => {
-    if (data._indexType !== '') {
+    // prevent delete index trigger fetching index status
+    if (data._indexType !== '' && status !== 'delete') {
```
Comment (shanghaikid) [inline client/src/pages/schema/IndexTypeElement.tsx:96]: Can we have enum for empty status and delete status, eg: STATUS.EMPTY , STATUS.DELETE

**Review by shanghaikid — CHANGES_REQUESTED** [review]

File: client/src/pages/schema/IndexTypeElement.tsx (hunk 1 above)
Comment (Tumao727) [reply client/src/pages/schema/IndexTypeElement.tsx:96]: Milvus has index status enum, but `empty` and `delete` status only needed for ui. Do you think it's better to add them?

indexStatus

Comment (shanghaikid) [reply client/src/pages/schema/IndexTypeElement.tsx:96]: Yeah, I think so.  You can leave a comment on these status, they are UI only.

**Review by shanghaikid — APPROVED** [review]

File: client/src/pages/schema/IndexTypeElement.tsx [hunk 2]
```diff
@@ -86,18 +92,15 @@ const IndexTypeElement: FC<{
   const DeleteIcon = icons.delete;
 
   const fetchStatus = useCallback(async () => {
-    if (data._indexType !== '') {
+    // prevent delete index trigger fetching index status
+    if (data._indexType !== '' && status !== IndexState.Delete) {
```
Comment (nameczz) [inline client/src/pages/schema/IndexTypeElement.tsx:96]: Default state here ?

Comment (Tumao727) [reply client/src/pages/schema/IndexTypeElement.tsx:96]: `indexType` is not index status. If no index, it will be empty string, otherwise it should return index type name like `FLAT`

**Review by nameczz — APPROVED** [review]
