### PR TITLE
Impore table sort

### LINKED ISSUE #221: Set the default sort for data like Collection | partition list.
**Describe the bug:**
Now every time, you get collection with different order

**Steps to reproduce:**
1. Collection list
2. Refresh page
3. The collection order is different

**Milvus-insight version:**

**Milvus version:**
milvus-2.0-rc4

### PR DESCRIPTION
**Pull request by nameczz**
it will sort all data, not current page data.

fix #221

### CODE REVIEW

File: client/src/components/grid/Table.tsx [hunk 1]
```diff
@@ -200,139 +194,133 @@ const EnhancedTable: FC<TableType> = props => {
...
               {rows && rows.length ? (
-                stableSort(rows, getComparator(order, orderBy)).map(
-                  (row, index) => {
-                    const isItemSelected = isSelected(row);
-                    const labelId = `enhanced-table-checkbox-${index}`;
+                rows.map((row, index) => {
+                  const isItemSelected = isSelected(row);
+                  const labelId = `enhanced-table-checkbox-${index}`;
+
+                  const handleMouseEnter = () => {
```
Comment (shanghaikid) [inline client/src/components/grid/Table.tsx:201]: please extract events out of each row

**Review by shanghaikid — CHANGES_REQUESTED** [review]

**Review by Tumao727 — APPROVED** [review]

**Review by shanghaikid — APPROVED** [review]
