### PR TITLE
fix pagination and update table style

### LINKED ISSUE #77: new partition won't be shown after creating
When I created a new partition, although the snack bar tells me that it have been successfully created, but I couldn't find it in the list.
Screen Shot 2021-06-25 at 2 18 02 PM

### PR DESCRIPTION
**Pull request by Tumao727**
fix #77 
partition

fix overview statistic card
overview

### CODE REVIEW

File: client/src/components/grid/Table.tsx [hunk 1]
```diff
@@ -145,7 +140,8 @@ const EnhancedTable: FC<TableType> = props => {
     if (setPageSize) {
       const containerHeight: number = (containerRef.current as any)!
         .offsetHeight;
-      const rowHeight: number = (rowRef.current as any)?.offsetHeight || 0;
+
+      const rowHeight = 54;
       const tableHeaderHeight: number = 57;
```
Comment (nameczz) [inline client/src/components/grid/Table.tsx:145]: Need some comments, explain the reason.

**Review by shanghaikid — APPROVED** [review]

**Review by nameczz — APPROVED** [review]
