### PR TITLE
Fix vector search style problem and update insert uploading validation check warning

### LINKED ISSUE #169: Vector search: the top box gets more padding after selecting the field
Before
image
After
image

### LINKED ISSUE #171: Vector search: when there is no collection, it shouldn't be a blank dropdown.
image

We should tell user, `No collection`

### PR DESCRIPTION
**Pull request by Tumao727**
### 1. fix #169 
**before selecting field:**
before
**after selecting field:**
after

### 2. fix #171 
no collection

### 3. update insert uploading check
  **1. disable uploader if user doesn't choose collection**
upload disable

  **2. change warning message if user uploaded `is_primary_key` and `autoID` both true field**
auto id warning

### CODE REVIEW

**Review by congtan0224 — APPROVED** [review]

**Review by nameczz — APPROVED** [review]

File: client/src/pages/seach/VectorSearch.tsx [hunk 1]
```diff
@@ -295,7 +295,12 @@ const VectorSearch = () => {
             options={collectionOptions}
             wrapperClass={classes.selector}
             variant="filled"
-            label={searchTrans('collection')}
+            label={
+              collectionOptions.length === 0
```
Comment (shanghaikid) [inline client/src/pages/seach/VectorSearch.tsx:299]: searchTrans(collectionOptions.length === 0 ? 'noCollection' : 'collection')

File: client/src/pages/seach/SearchParams.tsx [hunk 2]
```diff
@@ -138,7 +138,8 @@ const SearchParams: FC<SearchParamsProps> = ({
   const getSearchInputConfig = useCallback(
     (paramKey: searchKeywordsType): ITextfieldConfig => {
       const nlist = Number(
-        indexParams.find(p => p.key === 'nlist')?.value || 0
+        // nlist range is [1, 65536], if user didn't create index, we set 1024 as default nlist value
+        indexParams.find(p => p.key === 'nlist')?.value || 1024
```
Comment (shanghaikid) [inline client/src/pages/seach/SearchParams.tsx:142]: 1024 should be a constant

**Review by shanghaikid — CHANGES_REQUESTED** [review]

**Review by shanghaikid — APPROVED** [review]
